services:
  f1-backend:
    build:
      context: ../f1-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    restart: unless-stopped
    networks:
      - f1-internal

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - f1-internal

  f1-frontend:
    build:
      context: ../f1-frontend
    ports:
      - "8081:80"
    depends_on:
      - f1-backend
    restart: unless-stopped
    networks:
      - f1-internal

volumes:
  redis-data:

networks:
  f1-internal: