services:
  f1-backend:
    build: ../f1-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
      image: redis
      volumes:
          - redis-data:/data
      ports:
        - "6379:6379"

  f1-frontend:
    build: ../f1-frontend
    ports:
      - "8080:8080"
    depends_on:
      - f1-backend

volumes:
    redis-data: